#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : statsd
Version  : 3.2.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/48/5f/9b62d3edf46d4f781be77fcd5014ab6c8945c0c991f5a26628d7d5eaf69c/statsd-3.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/48/5f/9b62d3edf46d4f781be77fcd5014ab6c8945c0c991f5a26628d7d5eaf69c/statsd-3.2.2.tar.gz
Summary  : A simple statsd client.
Group    : Development/Tools
License  : MIT
Requires: statsd-python3
Requires: statsd-python
BuildRequires : buildreq-distutils3
BuildRequires : nose
BuildRequires : python-mock

%description
A Python statsd client
        ======================
        
        statsd_ is a friendly front-end to Graphite_. This is a Python client
        for the statsd daemon.

%package python
Summary: python components for the statsd package.
Group: Default
Requires: statsd-python3

%description python
python components for the statsd package.


%package python3
Summary: python3 components for the statsd package.
Group: Default
Requires: python3-core

%description python3
python3 components for the statsd package.


%prep
%setup -q -n statsd-3.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533785630
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
